#!/usr/bin/env python3
"""
Add Z.ai metadata to PDF files
Usage: python add_zai_metadata.py <pdf_file> [-t "Custom Title"]
"""
import sys
import os
from pypdf import PdfReader, PdfWriter

def add_metadata(input_path, title=None, output_path=None):
    """Add Z.ai metadata to PDF"""
    if not os.path.exists(input_path):
        print(f"Error: File not found: {input_path}")
        return False
    
    # Use input path as output if not specified
    if output_path is None:
        output_path = input_path
    
    # Get title from filename if not specified
    if title is None:
        title = os.path.splitext(os.path.basename(input_path))[0]
    
    try:
        reader = PdfReader(input_path)
        writer = PdfWriter()
        
        # Copy all pages
        for page in reader.pages:
            writer.add_page(page)
        
        # Add metadata
        writer.add_metadata({
            '/Title': title,
            '/Author': 'Z.ai',
            '/Creator': 'Z.ai',
            '/Subject': 'Generated by Z.ai'
        })
        
        # Write output
        with open(output_path, 'wb') as f:
            writer.write(f)
        
        print(f"✓ Metadata added: {output_path}")
        return True
    except Exception as e:
        print(f"Error: {e}")
        return False

def main():
    if len(sys.argv) < 2:
        print("Usage: python add_zai_metadata.py <pdf_file> [-t title] [-o output]")
        sys.exit(1)
    
    input_path = sys.argv[1]
    title = None
    output_path = None
    
    i = 2
    while i < len(sys.argv):
        if sys.argv[i] == '-t' and i + 1 < len(sys.argv):
            title = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] == '-o' and i + 1 < len(sys.argv):
            output_path = sys.argv[i + 1]
            i += 2
        else:
            i += 1
    
    add_metadata(input_path, title, output_path)

if __name__ == '__main__':
    main()
